### PR TITLE
github.com/uber-go/multierr expects import "go.uber.org/multierr"

### PR DESCRIPTION
**Pull request by koshatul**
I still can't get it to work, but I'll bug you about that later.

For now this is the uber library name change so at least it runs.

### CODE REVIEW

**Comment by jmalloc** [comment]
> I still can't get it to work,

"it" being this library?

**Comment by koshatul** [comment]
Yup, I can't quite follow how it's meant to work, but the Do() method on amqp seems to create a channel then wait for something to be added to it, but it isn't passed onto anything else to actually do work with it.

**Comment by jmalloc** [comment]
You have to run `Locker.Run()` it its own goroutine before calling `Do()`.

**Comment by koshatul** [comment]
Oh, that makes sense.

Here's the test I got working, seems to work as expected.

```
$ docker run -d --name snowflake-test -p 15672:15672 -p 5672:5672 --env RABBITMQ_DEFAULT_USER=test --env RABBITMQ_DEFAULT_PASS=test rabbitmq:3-management
```

```
func main() {
	logrus.Debug("snowflakeCommand():start")

	logrus.Debugf("Creating Context")
	ctx := context.Background()

	logrus.Debugf("Creating Locker")
	locker := &snowflakeamqp.Locker{
		DSN: "amqp://test:test@localhost:5672/",
	}

	logrus.Debugf("locker.Run(ctx)")
	go func() {
		err := locker.Run(ctx)
		if err != nil {
			logrus.Panic(err)
		}
	}()

	logrus.Debugf("Creating snowflakeFunc")
	snowflakeFunc := func(ctx context.Context) {
		logrus.Infof("Starting App")
		time.Sleep(10 * time.Second)
	}

	logrus.Debugf("locker.Do(ctx, test, snowflakeFunc)")
	locker.Do(
		ctx,
		"test",
		snowflakeFunc,
	)

	logrus.Debug("snowflakeCommand():end")
}
```

The goroutine around locker.Do is what I was missing.

**Pull request merged**
